### PR TITLE
ci: use ruff formatter

### PR DESCRIPTION
**Pull request by joelynch**
The ruff formatter is much faster than using black and isort.

### CODE REVIEW

**Comment by dmitry-potepalov** [comment]
I'll check it out and see whether I run into any issues with my env

**Review by dmitry-potepalov — CHANGES_REQUESTED** [review]
this breaks import sorting, because import sorting is a part of the ruff linter, not the formatter :( .

**Comment by joelynch** [comment]
> this breaks import sorting, because import sorting is a part of the ruff linter, not the formatter :( .

Okay I have put isort back in since ruff linting is a lot of changes.  In a future PR I will do ruff linting.

**Review by dmitry-potepalov — APPROVED** [review]
LGTM

**Pull request merged**
